/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prod.views;
import prod.controllers.MainControlador;
import prod.models.MainModelo;

/**
 *
 * @author PC_12
 */
public class MainVista extends javax.swing.JFrame {

    MainControlador viewController;
    MainModelo viewModelo = new MainModelo();
    /**
     * Creates new form MainVista
     */
    public MainVista() {
        initComponents();
        viewController = new MainControlador(viewModelo,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmAddPaciente = new javax.swing.JMenuItem();
        itmViewPacientes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itmContratar = new javax.swing.JMenuItem();
        itmViewDoctores = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itmAddCitaMedica = new javax.swing.JMenuItem();
        itmViewCitasMedicas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        itmEditClinica = new javax.swing.JMenuItem();
        itmViewClinica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnOpenInstructivo = new javax.swing.JMenuItem();
        btnOpenAcrcaDe = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Insumo 2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFORMÁTICA");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insumo 2");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prod/assets/Imgs/logouets.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema de Gestión de Clínicas");

        jMenu1.setText("Pacientes");

        itmAddPaciente.setText("Registrar Paciente");
        itmAddPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddPacienteActionPerformed(evt);
            }
        });
        jMenu1.add(itmAddPaciente);

        itmViewPacientes.setText("Ver Pacientes");
        jMenu1.add(itmViewPacientes);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Doctores");

        itmContratar.setText("Contratar ");
        jMenu5.add(itmContratar);

        itmViewDoctores.setText("Ver Doctores");
        jMenu5.add(itmViewDoctores);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Citas Médicas");

        itmAddCitaMedica.setText("Crear");
        jMenu6.add(itmAddCitaMedica);

        itmViewCitasMedicas.setText("Ver Todas las Citas");
        jMenu6.add(itmViewCitasMedicas);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Gestion ");

        itmEditClinica.setText("Editar Clinica");
        itmEditClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEditClinicaActionPerformed(evt);
            }
        });
        jMenu7.add(itmEditClinica);

        itmViewClinica.setText("Datos de la Clinica");
        jMenu7.add(itmViewClinica);

        jMenuBar1.add(jMenu7);

        jMenu2.setText("Ayuda");

        btnOpenInstructivo.setText("Instructivo");
        btnOpenInstructivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenInstructivoActionPerformed(evt);
            }
        });
        jMenu2.add(btnOpenInstructivo);

        btnOpenAcrcaDe.setText("Acerca de");
        btnOpenAcrcaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenAcrcaDeActionPerformed(evt);
            }
        });
        jMenu2.add(btnOpenAcrcaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(183, 183, 183)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenInstructivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenInstructivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenInstructivoActionPerformed

    private void btnOpenAcrcaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenAcrcaDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenAcrcaDeActionPerformed

    private void itmAddPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAddPacienteActionPerformed

    private void itmEditClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEditClinicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmEditClinicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem btnOpenAcrcaDe;
    public javax.swing.JMenuItem btnOpenInstructivo;
    public javax.swing.JMenuItem itmAddCitaMedica;
    public javax.swing.JMenuItem itmAddPaciente;
    public javax.swing.JMenuItem itmContratar;
    public javax.swing.JMenuItem itmEditClinica;
    public javax.swing.JMenuItem itmViewCitasMedicas;
    public javax.swing.JMenuItem itmViewClinica;
    public javax.swing.JMenuItem itmViewDoctores;
    public javax.swing.JMenuItem itmViewPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
